    
<JoinGame>:
    Label:
        pos_hint: {'x':.35,'y':.5}
        size_hint: .2, .05
        text: '[b][color=000000]Game Name: [/color][\b]'
        markup: True
    TextInput:
        pos_hint: {'x':.5,'y':.5}
        size_hint: .2, .05
        id: gameName
    Button:
        pos_hint: {'x':.5,'y':.4}
        size_hint: .2, .1
        text: "Join game"
        # on_press: app.ButtonSound(), root.join()