<PlayingMode>:
    BoxLayout:
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint: .4,.3
        orientation: 'vertical'

        Button:
            text: "Multiplayer"
            on_press: 
                if app.is_logged(): app.manager.push("CreateOrJoin")
                else: root.ModePopup()
                    
        Button:
            text: "Singleplayer"
            on_press:
                app.manager.push("CreateSPGame"), app.ButtonSound()